global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#anton_kurkin'
