version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db
  ui:
    image: ${USERNAME}/ui:${UI_VERSION}
    ports:
      - ${HOST_PORT}:${DOCKER_PORT}/tcp
    networks:
      - front_net
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9292
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${USERNAME}/post:${POST_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - POST_DATABASE_HOST=post_db
      - POST_DATABASE=posts
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post_db
    ports:
      - "5000:5000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ${USERNAME}/comment:${COMMENT_VERSION}
    networks:
      - back_net
      - front_net
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
volumes:
  prometheus_data:
  post_db:
networks:
  back_net:
    ipam:
      config:
        - subnet: 10.0.2.0/24
  front_net:
    ipam:
      config:
        - subnet: 10.0.1.0/24
